Запуск функции: norm_func с аргументами: (10, 2), {}
Функция: norm_func вернула: 12
Ошибка в функции: error_func с аргументами: (1, 0), {}
Запуск функции: norm_func с аргументами: (10, 2), {}
Функция: norm_func вернула: 12
Ошибка в функции: error_func с аргументами: (1, 0), {}
Запуск функции: norm_func с аргументами: (10, 2), {}
Функция: norm_func вернула: 12
Ошибка в функции: error_func с аргументами: (1, 0), {}
Запуск функции: norm_func с аргументами: (10, 2), {}
Функция: norm_func вернула: 12
